import { Box, Text, HStack, Badge, VStack } from "@chakra-ui/react";
import { LuSparkles } from "react-icons/lu";
import { MockupContainer } from "./MockupContainer";

const SUGGESTIONS = [
  {
    text: "Confirmer la commande",
    confidence: 0.95,
    notes:
      "Standard commercial term used by the majority of French online stores.",
  },
  {
    text: "Valider ma commande",
    confidence: 0.88,
    notes:
      "More personal and engaging phrasing, very common in e-commerce.",
  },
  {
    text: "Passer la commande",
    confidence: 0.74,
    notes:
      "Idiomatic expression that emphasises the action rather than the confirmation.",
  },
];

export function AiSuggestionsMockup() {
  return (
    <MockupContainer url="transi-store.com/orgs/acme/projects/webapp/keys/37">
      <Box p={4} pointerEvents="none">
        {/* Header */}
        <HStack mb={3} gap={2}>
          <LuSparkles />
          <Text fontWeight="semibold">AI Translation Suggestions</Text>
          <Badge colorPalette="purple">FR</Badge>
        </HStack>

        {/* Source key & value */}
        <HStack mb={1} fontSize="sm" gap={2} flexWrap="wrap">
          <Text fontFamily="mono" color="fg.muted">
            checkout.confirm_button
          </Text>
          <Text color="fg.muted">→</Text>
          <Text fontStyle="italic" color="fg">
            &quot;Confirm order&quot;
          </Text>
        </HStack>

        {/* Provider attribution */}
        <Text fontSize="xs" color="fg.subtle" mb={4}>
          Generated by Google Gemini 2.0 Flash
        </Text>

        {/* Suggestions list */}
        <VStack align="stretch" gap={3}>
          {SUGGESTIONS.map((suggestion, index) => (
            <Box
              key={index}
              p={4}
              borderWidth={1}
              borderRadius="md"
              _hover={{ bg: "bg.muted", cursor: "pointer" }}
            >
              <Text fontFamily="mono" fontSize="sm">
                {suggestion.text}
              </Text>
              <Text fontSize="xs" color="fg.subtle" mt={1}>
                Confidence: {Math.round(suggestion.confidence * 100)}%
              </Text>
              {suggestion.notes && (
                <Box mt={2} p={2} bg="bg.subtle" borderRadius="sm">
                  <Text fontSize="xs" color="fg.muted">
                    {suggestion.notes}
                  </Text>
                </Box>
              )}
            </Box>
          ))}
        </VStack>

        <Text fontSize="xs" color="fg.subtle" mt={3}>
          Click on a suggestion to apply it to the translation field.
        </Text>
      </Box>
    </MockupContainer>
  );
}
