name: Release CLI

on:
  push:
    branches:
      - main
  workflow_dispatch: ~

permissions:
  id-token: write # Required for npm provenance
  contents: write # to create a release commit and tag
  pull-requests: write # to create a release pull request if there are changesets

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Build & Publish @transi-store/cli to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Init repository dependencies
        uses: ./.github/actions/setup-project

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
